### ISSUE TITLE
Namespace is not defined for type "org.accordproject.contract.*".

### ISSUE THREAD

**Issue by martinhalford** [accordproject/concerto-codegen#1]
While writing Visitor for Rust land, came across this error for a supposedly valid model file.

## Context
Run this code in root of `concerto-codegen` repo.

```
'use strict';

const { ModelManager } = require('@accordproject/concerto-core');
const { FileWriter } = require('@accordproject/concerto-util');

const Visitor = require('./lib/codegen/fromcto/jsonschema/jsonschemavisitor');

const model = `namespace org.accordproject.helloworld@0.14.0

import org.accordproject.contract.* from https://models.accordproject.org/accordproject/contract.cto
import org.accordproject.runtime.* from https://models.accordproject.org/accordproject/runtime.cto

transaction MyRequest extends Request {
  o String input
}

transaction MyResponse extends Response {
  o String output
}

asset HelloWorldClause extends Clause {
  o String name
}`;

const modelManager = new ModelManager();
modelManager.addCTOModel(model);

const parameters = {
  fileWriter: new FileWriter('./output')
};
const visitor = new Visitor();

modelManager.accept(visitor, parameters);

console.log('Done');
```

## Expected Behavior
As this is a valid model then expected the model to be validated by `basemodelmanager.js`.

## Actual Behavior
The `basemodelmanager.js` throw an error on line 201 `modelFile.validate();`.

```
IllegalModelException: Namespace is not defined for type "org.accordproject.contract.*". 
    at /Users/martin/Dev/accord/concerto-codegen/node_modules/@accordproject/concerto-core/lib/introspect/modelfile.js:233:23
    at Array.forEach (<anonymous>)
    at ModelFile.validate (/Users/martin/Dev/accord/concerto-codegen/node_modules/@accordproject/concerto-core/lib/introspect/modelfile.js:225:27)
    at ModelManager.addModelFile (/Users/martin/Dev/accord/concerto-codegen/node_modules/@accordproject/concerto-core/lib/basemodelmanager.js:201:27)
    at ModelManager.addModel (/Users/martin/Dev/accord/concerto-codegen/node_modules/@accordproject/concerto-core/lib/basemodelmanager.js:234:14)
    at ModelManager.addCTOModel (/Users/martin/Dev/accord/concerto-codegen/node_modules/@accordproject/concerto-core/lib/modelmanager.js:80:21)
    at Object.<anonymous> (/Users/martin/Dev/accord/concerto-codegen/testharness.js:30:14)
    at Module._compile (node:internal/modules/cjs/loader:1246:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1300:10)
    at Module.load (node:internal/modules/cjs/loader:1103:32) {
  component: '@accordproject/concerto-util',
  fileLocation: undefined,
  shortMessage: 'Namespace is not defined for type "org.accordproject.contract.*".',
  fileName: null
}
```

**Comment by mttrbrts** [comment]
In the context, you'll need to explicitly add the runtime and contract models to the model manager.

**Comment by martinhalford** [comment]
OK. I'll give that a try. Thanks.
